### ISSUE TITLE
Exec failure on Node 21

### ISSUE THREAD

**Issue by skeet70** [shelljs/shelljs#1143]
### Node version (or tell us if you're using electron or some other framework):

`21.3.0`

### ShellJS version (the most recent version/Github branch you see the bug on):

`0.8.5`

### Operating system:

NixOS and Ubuntu 22.04

### Description of the bug:

[A script](https://github.com/IronCoreLabs/recrypt-node-binding/blob/main/publish.js) that [ran fine in Node 16/18/20 errors when run in Node 21](https://github.com/IronCoreLabs/recrypt-node-binding/actions/runs/7091540972).

```
[nix-shell:~/code/ironcore/recrypt-node-binding]$ node publish.js
/home/mumu/code/ironcore/recrypt-node-binding/node_modules/shelljs/src/common.js:399
        throw e;
        ^

Error [ShellJSInternalError]: ENOENT: no such file or directory, open '/run/user/1000/shelljs_6f547a18b9ffbc16419a'
    at Object.writeFileSync (node:fs:2352:20)
    at writeFileLockedDown (/home/mumu/code/ironcore/recrypt-node-binding/node_modules/shelljs/src/exec.js:61:8)
    at execSync (/home/mumu/code/ironcore/recrypt-node-binding/node_modules/shelljs/src/exec.js:66:3)
    at Object._exec (/home/mumu/code/ironcore/recrypt-node-binding/node_modules/shelljs/src/exec.js:223:12)
    at Object.exec (/home/mumu/code/ironcore/recrypt-node-binding/node_modules/shelljs/src/common.js:335:23)
    at Object.<anonymous> (/home/mumu/code/ironcore/recrypt-node-binding/publish.js:31:7)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/run/user/1000/shelljs_6f547a18b9ffbc16419a'
}

Node.js v21.3.0
```

### Example ShellJS command to reproduce the error:

```javascript
shell.exec("yarn install --ignore-scripts");
```

**Comment by nfischer** [comment]
I'm going to close this as wontfix. As discussed on #1144, this issue was a nodejs bug that was fixed in 21.4 so there's no need to patch shelljs.
