### ISSUE TITLE
"exec" causes LiveScript interpreter (lsc) to hang

### ISSUE THREAD

**Issue by gkovacs** [shelljs/shelljs#160]
I'm using a CoffeeScript dialect called LiveScript: http://livescript.net/ . A test case is below, executing it either in the interactive LiveScript interpreter or by saving it to test.ls and running with lsc test.ls causes it to hang after outputting "foo" and "bar" (so it's hanging on the shell.exec call).

console.log 'foo'
shell = require('shelljs')
console.log 'bar'
console.log shell.exec('ls')
console.log 'baz'

To test, save to test.ls and run with lsc test.ls.

Interestingly the code above works fine when pre-compiling the LiveScript to Javascript and executing with node, so it might actually be an issue with lsc: "lsc -c test.ls && node test.js" runs correctly.

**Comment by ariporad** [comment]
@gkovacs: Would you mind re-testing this with the latest version of shelljs? Thanks!

**Comment by gkovacs** [comment]
not hanging anymore, but giving a stacktrace instead:

$ lsc
LiveScript 1.4.0 - use 'lsc --help' for more information
ls> require('shelljs').exec('ls')
Failed at: /var/folders/9y/khkqwm9n23nfx4m794l7n90r0000gn/T/shelljs_9cd0cb6c7a9cc65959c6
[Error: Parse error on line 1: Unexpected ','
at /var/folders/9y/khkqwm9n23nfx4m794l7n90r0000gn/T/shelljs_9cd0cb6c7a9cc65959c6]
shell.js: internal error
Error: Command failed: "/usr/local/bin/lsc" /var/folders/9y/khkqwm9n23nfx4m794l7n90r0000gn/T/shelljs_9cd0cb6c7a9cc65959c6
    at checkExecSyncError (child_process.js:1346:13)
    at Object.execSync (child_process.js:1386:13)
    at execSync (/Users/geza/test-shelljs/node_modules/shelljs/src/exec.js:81:11)
    at Object._exec (/Users/geza/test-shelljs/node_modules/shelljs/src/exec.js:214:12)
    at Object.exec (/Users/geza/test-shelljs/node_modules/shelljs/src/common.js:182:23)
    at repl:2:20
    at ContextifyScript.Script.runInNewContext (vm.js:38:15)
    at Object.exports.runInNewContext (vm.js:69:17)
    at Interface.<anonymous> (/usr/local/lib/node_modules/livescript/lib/command.js:478:18)
    at Interface.emit (events.js:107:17)

Failed at: /var/folders/9y/khkqwm9n23nfx4m794l7n90r0000gn/T/shelljs_e7417ee308f2194010e5
[Error: Parse error on line 1: Unexpected ','
at /var/folders/9y/khkqwm9n23nfx4m794l7n90r0000gn/T/shelljs_e7417ee308f2194010e5]
shell.js: internal error
Error: Command failed: "/usr/local/bin/lsc" /var/folders/9y/khkqwm9n23nfx4m794l7n90r0000gn/T/shelljs_e7417ee308f2194010e5
    at checkExecSyncError (child_process.js:1346:13)
    at Object.execSync (child_process.js:1386:13)
    at execSync (/Users/geza/test-shelljs/node_modules/shelljs/src/exec.js:81:11)
    at Object._exec (/Users/geza/test-shelljs/node_modules/shelljs/src/exec.js:214:12)
    at Object.exec (/Users/geza/test-shelljs/node_modules/shelljs/src/common.js:182:23)
    at repl:2:20
    at ContextifyScript.Script.runInNewContext (vm.js:38:15)
    at Object.exports.runInNewContext (vm.js:69:17)
    at Interface.<anonymous> (/usr/local/lib/node_modules/livescript/lib/command.js:478:18)
    at Interface.emit (events.js:107:17)

**Comment by gkovacs** [comment]
The issue is that when using lsc, process.execPath is /usr/local/bin/lsc instead of the path to node (it is /usr/local/bin/node when using both coffee or node, which is what shelljs seems to expect)

As you'll see explained at https://github.com/gkz/LiveScript/issues/562 if I modify the livescript interpreter to set process.execPath to /usr/local/bin/lsc then it fixes the issue.

Unfortunately the livescript folks don't seem to want to change the process.execPath to match coffee's behavior so shelljs doesn't work when executed from lsc.

**Comment by nfischer** [comment]
So it sounds like this is an issue with lsc? Currently, we only support js and coffeescript, not the others

**Comment by nfischer** [comment]
@gkovacs is this resolved now that gkz/LiveScript#822 is merged?

**Comment by gkovacs** [comment]
yes it is resolved now
