### ISSUE TITLE
Command can't have \n

### ISSUE THREAD

**Issue by fenuks** [shelljs/shelljs#175]
exec hang when executing command with /n. Its probably because wrong escaping.
E.g. this will hang: 

``` javascript
syncExec = require('shelljs').exec
var command = "python2 -c 'print \"first line\"\nprint \"second line\"'"
out = syncExec(command2)
```

Child_process.exec works just fine.

**Comment by stevemao** [comment]
Is this problem solved?

**Comment by stevemao** [comment]
You should probably use `\\n`?

**Comment by stevemao** [comment]
Apparently travis does not like newline `$'\n'`

https://github.com/travis-ci/travis-ci/issues/4061

Have to use `child.exec` for now :(

**Comment by eiabea** [comment]
I ran into the same issue :-(

Do you have any plans to work on this issue?

**Comment by mtscout6** [comment]
I tried running this locally, though my understanding of python is limited. I get the following when just running the command outside of node:

```
➜  shelljs git:(master) ✗ python -c 'print "first line"\nprint "second line"'
  File "<string>", line 1
    print "first line"\nprint "second line"
                                          ^
SyntaxError: unexpected character after line continuation character
```

So it would appear to me that your example is an invalid python example?

**Comment by danasilver** [comment]
I can reproduce this:

```
var sh = require('shelljs');

sh.exec('echo "\n"');

var childProcess = child.exec('echo \"
                              ^^^^^^^^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
shell.js: internal error
Error: Command failed: "/Users/dsilver/.nvm/versions/node/v4.2.1/bin/node" /var/folders/vz/x698bjq50z55rz4xpm66fy000000gn/T/shelljs_9acc94d83ef8d84fbb8c
    at checkExecSyncError (child_process.js:441:13)
    at Object.execSync (child_process.js:481:13)
    at execSync (/Users/dsilver/Documents/workspace/shelljs/src/exec.js:81:11)
    at Object._exec (/Users/dsilver/Documents/workspace/shelljs/src/exec.js:214:12)
    at Object.exec (/Users/dsilver/Documents/workspace/shelljs/src/common.js:182:23)
    at repl:1:4
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:393:12)
```

The issue is in the [escape function](https://github.com/shelljs/shelljs/blob/a38ef4557e8658dec9409a034b31c70d8646e7de/src/exec.js#L39-L41) in exec.js. In `String.replace` regex, `\n` is interpreted as a single character, so the `\` in `\n` is not replaced by the first replace call. I think the best fix for this is using a regular expression that matches each of the [single character escape sequences](https://mathiasbynens.be/notes/javascript-escapes#single) and calling a function as the second argument to `replace` as done in jsesc ([1](https://github.com/mathiasbynens/jsesc/blob/master/src/jsesc.js#L71-L84), [2](https://github.com/mathiasbynens/jsesc/blob/master/src/jsesc.js#L222-L226)).

I'm working on this fix for a PR.

**Comment by nfischer** [comment]
@mtscout6 turns out, this actually is a valid `python2` command (I didn't believe it at first either!). The `\n` in the javascript string gets expanded into a real newline (the `\n` in your shell command wouldn't get expanded properly on bash). What it really looks like in the shell is:

```Bash
$ python2 -c 'print "first line"
print "second line"'
```

@danasilver I assume your example is supposed to translate into:

```Bash
$ echo "
"
```

Or is it supposed to translate to `echo "\n"`? The latter case doesn't make much sense in bash, since that *should* print a literal `\n`, not a newline.

Either way, I agree that `exec()` doesn't seem to behave sensibly. This might be related to the call to `escape()` [here](https://github.com/shelljs/shelljs/blob/master/src/exec.js#L72).

**Comment by nfischer** [comment]
Due to the design for `shell.exec()`, we unfortunately can't provide good support for parameters with newlines. This will be something we support with a replacement for the `exec` API (see #524 for a WIP).

Given that, I'm bumping the milestone back to match that PR.

**Comment by nfischer** [comment]
This is an explicit design goal of https://shelljs.page.link/cmd-design. See:

> Error-prone and inconvenient to escape shell-specific syntax (e.g., `filename` is meant to refer to a file literally named `file\nWith"$pecial; chars.txt`)

I'm not sure yet if this will be achievable on Windows--we *may* use [puka](https://www.npmjs.com/package/puka#whats-the-catch) on Windows, and it explicitly mentions newlines ("line breaks") as problematic characters.

I'll add a test case for this in #866 if this is achievable on Windows. At which point I'll merge this into #495.

**Comment by jeffrey-aguilera** [comment]
How is this still open after four years?

**Comment by nfischer** [comment]
Can you try this out in the latest ShellJS release (v0.9.1) and let me know if that fixed the problem?

This should be supported by the new [`shell.cmd()`](https://github.com/shelljs/shelljs#cmdarg1-arg2---options) function, which is intended as the replacement for most uses of `shell.exec()`.
