### ISSUE TITLE
exec command not working. Showing "shell.js : internal error" in nwjs

### ISSUE THREAD

**Issue by dvenkatsagar** [shelljs/shelljs#248]
Im trying to do a basic command taken from the documentation.

``` javascript
var version = exec('node --version', {silent:true}).output;
```

and it shows the following output

``` bash
[23008:1031/205417:INFO:CONSOLE(191)] ""shell.js: internal error"", source: /home/sagar/Repositories/Scripts/Projects/node/ubic/ubic/node_modules/shelljs/src/common.js (191)
[23008:1031/205417:INFO:CONSOLE(192)] ""Error: ENOENT: no such file or directory, open '/tmp/shelljs_7712d2f4992c056323b3'\n    at Error (native)\n    at Object.fs.openSync (fs.js:540:18)\n    at Object.fs.readFileSync (fs.js:392:15)\n    at execSync (/home/sagar/Repositories/Scripts/Projects/node/ubic/ubic/node_modules/shelljs/src/exec.js:109:24)\n    at Object._exec (/home/sagar/Repositories/Scripts/Projects/node/ubic/ubic/node_modules/shelljs/src/exec.js:214:12)\n    at Object.exec (/home/sagar/Repositories/Scripts/Projects/node/ubic/ubic/node_modules/shelljs/src/common.js:182:23)\n    at file:///home/sagar/Repositories/Scripts/Projects/node/ubic/ubic/main.js:34:21"", source: /home/sagar/Repositories/Scripts/Projects/node/ubic/ubic/node_modules/shelljs/src/common.js (192)
```

Can some one please help me out? I just don't understand where Im going wrong. It works fine when I use the asynchronous way. 

Edit : I forgot to mention that Im trying this in nwjs.

Update: Ok I understood that, it works well with nodejs, but for some reason, it doesn't work when using nwjs.

**Comment by nfischer** [comment]
@dvenkatsagar could you test this out again on ShellJS v0.6? If the error persists, we can investigate

**Comment by dvenkatsagar** [comment]
Nope the problem still exists even with 0.6.0.

**Comment by nfischer** [comment]
Looks like something we should try to roll into v0.7, since it's looking like that'll mainly cover `exec`-related stuff.

@dvenkatsagar could you try running this with async `exec`? My suspicion is that it will succeed for async and fail for sync.

**Comment by dvenkatsagar** [comment]
Yes @nfischer , that is true, for `async:true`, it works, but when kept `false`, it doesn't work.

**Comment by nfischer** [comment]
@dvenkatsagar thanks! That means it's specific to the implementation of `execSync` that we use. It uses files to do a busy-wait to make things synchronous. I'm not experienced with electron or nwjs, so if there's any way you could investigate, we'll probably find a solution a bit quicker. Or if @ariporad could investigate

**Comment by Rawnly** [comment]
Got the same error with electron and the latest version of **shelljs**. But when async and the app is built then log white space. What this can be?

That's my function
```js
var install_splash = () => {
  if (!cmd.which('splash')) {
    cmd.exec('npm i -g splash-cli', {silent:true, async:true}, (err, data) => {
      console.log(data);  //=> this return ''
      if ( cmd.which('splash') ) {
        _photo[4].enabled = false
      }
    });
  } else {
    _photo[4].enabled = false
    console.log('Splash is installed');
  }
}
```

The latest (line 205) is this function
![devtools](https://cloud.githubusercontent.com/assets/16429579/22002701/425c1a84-dc4e-11e6-8050-f6e6f7abec72.png)

**Comment by nfischer** [comment]
Closing this. As with electron, we don't support nw.js. We do provide a wiki page documenting workarounds for electron which may or may not be helpful hints for how to workaround this.

If someone still encounters this bug and has an idea for how to solve it, I'll gladly take a look.
