### ISSUE TITLE
Shelljs quits unexpectedly:

### ISSUE THREAD

**Issue by dtruel** [shelljs/shelljs#300]
I have no idea why  - but this is the output

```
/tmp/shelljs_70dbcc9e7102d53da62f:4
  fs.writeFileSync('/tmp/shelljs_5942f59f9138177745a1', err ? err.code.toString() : '0');
                                                                      ^

TypeError: Cannot read property 'toString' of undefined
    at /tmp/shelljs_70dbcc9e7102d53da62f:4:71
    at ChildProcess.exithandler (child_process.js:210:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
shell.js: internal error
Error: Command failed: "/usr/bin/node" /tmp/shelljs_70dbcc9e7102d53da62f
    at checkExecSyncError (child_process.js:441:13)
    at Object.execSync (child_process.js:481:13)
    at execSync (/data_collection/node_modules/shelljs/src/exec.js:81:11)
    at _exec (/data_collection/node_modules/shelljs/src/exec.js:214:12)
    at /data_collection/node_modules/shelljs/src/common.js:182:23
    at run (/data_collection/MY_NODE_FILE.js:16:18)
    at Object.<anonymous> (/data_collection/tx_runAllMonthlyDataCollection.js:31:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

**Comment by nfischer** [comment]
The variable err is undefined. Where are you setting that value?

**Comment by dtruel** [comment]
I'm not setting it, however I am using this library:

https://www.npmjs.com/package/exec

I guess I'll post this there.

Thanks!
