### ISSUE TITLE
`mv` not working as expected on windows

### ISSUE THREAD

**Issue by marvindanig** [shelljs/shelljs#382]
I'm using shelljs to `mv` a folder to a trash subfolder with node CLI like so:

```
function deletePage(removeAt, callback) {

  var dateFormat = require('dateformat');
  var now = new Date();
  var timestamp = dateFormat(now, "isoDateTime");
  mv(path.join('manuscript', 'page-' + removeAt), path.join('trash', 'page-' + removeAt + '-' + timestamp));
  if (typeof callback === "function") {
    callback();
  }
}
```
This works as expected on linux and mac but is failing on windows. The folder to be moved exists at the given path and yet shelljs errors out. 

What am I doing wrong here? 

```
$ bookiza remove 13 
shell.js: internal error 
Error: ENOENT: no such file or directory, rename 'C:\Users\k3kish\Books\DMV-DL-Guide\manuscript\page-13' -> 'C:\Users\k3kish\Books\DMV-DL-Guide\trash\page-13-2016-03-02T22:16:40-0500' 
at Error (native) 
at Object.fs.renameSync (fs.js:729:18) 
at C:\Users\k3kish\AppData\Roaming\npm\node_modules\bookiza\node_modules\shelljs\src\mv.js:79:8 
at Array.forEach (native) 
at _mv (C:\Users\k3kish\AppData\Roaming\npm\node_modules\bookiza\node_modules\shelljs\src\mv.js:55:11) 
at C:\Users\k3kish\AppData\Roaming\npm\node_modules\bookiza\node_modules\shelljs\src\common.js:240:23
at deletePage (C:\Users\k3kish\AppData\Roaming\npm\node_modules\bookiza\lib\manager.js:294:3) 
at Object.removePage [as remove] (C:\Users\k3kish\AppData\Roaming\npm\node_modules\bookiza\lib\manager.js:270:3) 
at Command.<anonymous> (C:\Users\k3kish\AppData\Roaming\npm\node_modules\bookiza\bin\commands.js:80:16) 
    at Command.listener (C:\Users\k3kish\AppData\Roaming\npm\node_modules\bookiza\node_modules\commander\index.js:301:8)
```

**Comment by nfischer** [comment]
Hmm... we'll have to investigate. I work primarily on Linux, so if there's any diagnosing you could do, that might help.

**Comment by ariporad** [comment]
@marvindanig: I'm not a windows expert, but it might be the colons in the path. Can you try changing the timestamp format, and letting us know if it's still a problem?

Thanks!

**Comment by marvindanig** [comment]
:+1:  Yep, it was the colons in `isoDateTime` format. Changed it to an ordinary chain `dddd-mmmm-dS-yyyy-hh-MM-ss-TT` and it's working great now.

Great observation @ariporad :8ball:

**Comment by ariporad** [comment]
No problem. :smile:.
